version: '3'
networks:
  backend:
services:
  nginx:
    build:
      context: ./nginx
    networks:
      - backend
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    depends_on:
      - php-fpm
    volumes:
      - ${APPS_CODE_PATH_HOST}:${APPS_CODE_PATH_CONTAINER}
      - ${NGINX_SITES_CONF_PATH}:/etc/nginx/sites-available
  php-fpm:
    build:
      context: ./php-fpm
    networks:
      - backend
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ${APPS_CODE_PATH_HOST}:${APPS_CODE_PATH_CONTAINER}
  mariadb:
    build:
      context: ./mariadb
    networks:
      - backend
    volumes:
      - ${MARIADB_DATA_PATH_HOST}:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT_HOST}:3306
  redis:
    build:
      context: ./redis
    volumes:
      - ~/.wechat-library/data:/data
    networks:
      - backend
    ports:
      - ${REDIS_PORT_HOST}:6379
    
    